//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstonTech.Lottery.Web.ServiceLotteryLookup {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="LotteryGameDTOCollection", Namespace="http://schemas.datacontract.org/2004/07/AstonTech.Lottery.Services.DataContracts", ItemName="LotteryGameDTO")]
    [System.SerializableAttribute()]
    public class LotteryGameDTOCollection : System.Collections.Generic.List<AstonTech.Lottery.Web.ServiceLotteryLookup.LotteryGameDTO> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LotteryGameDTO", Namespace="http://schemas.datacontract.org/2004/07/AstonTech.Lottery.Services.DataContracts")]
    [System.SerializableAttribute()]
    public partial class LotteryGameDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameAbbreviationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LotteryGameIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameName {
            get {
                return this.GameNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GameNameField, value) != true)) {
                    this.GameNameField = value;
                    this.RaisePropertyChanged("GameName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameAbbreviation {
            get {
                return this.GameAbbreviationField;
            }
            set {
                if ((object.ReferenceEquals(this.GameAbbreviationField, value) != true))
                {
                    this.GameAbbreviationField = value;
                    this.RaisePropertyChanged("GameAbbreviation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LotteryGameId {
            get {
                return this.LotteryGameIdField;
            }
            set {
                if ((this.LotteryGameIdField.Equals(value) != true)) {
                    this.LotteryGameIdField = value;
                    this.RaisePropertyChanged("LotteryGameId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LotteryLookupServiceFault", Namespace="http://schemas.datacontract.org/2004/07/AstonTech.Lottery.Services.Faults")]
    [System.SerializableAttribute()]
    public partial class LotteryLookupServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceLotteryLookup.ILotteryLookupService")]
    public interface ILotteryLookupService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILotteryLookupService/GetLotteryGameCollection", ReplyAction="http://tempuri.org/ILotteryLookupService/GetLotteryGameCollectionResponse")]
        AstonTech.Lottery.Web.ServiceLotteryLookup.LotteryGameDTOCollection GetLotteryGameCollection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILotteryLookupService/GetLotteryGameCollection", ReplyAction="http://tempuri.org/ILotteryLookupService/GetLotteryGameCollectionResponse")]
        System.Threading.Tasks.Task<AstonTech.Lottery.Web.ServiceLotteryLookup.LotteryGameDTOCollection> GetLotteryGameCollectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILotteryLookupService/GetLotteryGame", ReplyAction="http://tempuri.org/ILotteryLookupService/GetLotteryGameResponse")]
        AstonTech.Lottery.Web.ServiceLotteryLookup.LotteryGameDTO GetLotteryGame(int lotteryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILotteryLookupService/GetLotteryGame", ReplyAction="http://tempuri.org/ILotteryLookupService/GetLotteryGameResponse")]
        System.Threading.Tasks.Task<AstonTech.Lottery.Web.ServiceLotteryLookup.LotteryGameDTO> GetLotteryGameAsync(int lotteryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILotteryLookupService/DeleteLotteryGame", ReplyAction="http://tempuri.org/ILotteryLookupService/DeleteLotteryGameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AstonTech.Lottery.Web.ServiceLotteryLookup.LotteryLookupServiceFault), Action="http://tempuri.org/ILotteryLookupService/DeleteLotteryGameLotteryLookupServiceFau" +
            "ltFault", Name="LotteryLookupServiceFault", Namespace="http://schemas.datacontract.org/2004/07/AstonTech.Lottery.Services.Faults")]
        void DeleteLotteryGame(int lotteryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILotteryLookupService/DeleteLotteryGame", ReplyAction="http://tempuri.org/ILotteryLookupService/DeleteLotteryGameResponse")]
        System.Threading.Tasks.Task DeleteLotteryGameAsync(int lotteryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILotteryLookupService/SaveLotteryGame", ReplyAction="http://tempuri.org/ILotteryLookupService/SaveLotteryGameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AstonTech.Lottery.Web.ServiceLotteryLookup.LotteryLookupServiceFault), Action="http://tempuri.org/ILotteryLookupService/SaveLotteryGameLotteryLookupServiceFault" +
            "Fault", Name="LotteryLookupServiceFault", Namespace="http://schemas.datacontract.org/2004/07/AstonTech.Lottery.Services.Faults")]
        void SaveLotteryGame(AstonTech.Lottery.Web.ServiceLotteryLookup.LotteryGameDTO gameToSave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILotteryLookupService/SaveLotteryGame", ReplyAction="http://tempuri.org/ILotteryLookupService/SaveLotteryGameResponse")]
        System.Threading.Tasks.Task SaveLotteryGameAsync(AstonTech.Lottery.Web.ServiceLotteryLookup.LotteryGameDTO gameToSave);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILotteryLookupServiceChannel : AstonTech.Lottery.Web.ServiceLotteryLookup.ILotteryLookupService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LotteryLookupServiceClient : System.ServiceModel.ClientBase<AstonTech.Lottery.Web.ServiceLotteryLookup.ILotteryLookupService>, AstonTech.Lottery.Web.ServiceLotteryLookup.ILotteryLookupService {
        
        public LotteryLookupServiceClient() {
        }
        
        public LotteryLookupServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LotteryLookupServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LotteryLookupServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LotteryLookupServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AstonTech.Lottery.Web.ServiceLotteryLookup.LotteryGameDTOCollection GetLotteryGameCollection() {
            return base.Channel.GetLotteryGameCollection();
        }
        
        public System.Threading.Tasks.Task<AstonTech.Lottery.Web.ServiceLotteryLookup.LotteryGameDTOCollection> GetLotteryGameCollectionAsync() {
            return base.Channel.GetLotteryGameCollectionAsync();
        }
        
        public AstonTech.Lottery.Web.ServiceLotteryLookup.LotteryGameDTO GetLotteryGame(int lotteryId) {
            return base.Channel.GetLotteryGame(lotteryId);
        }
        
        public System.Threading.Tasks.Task<AstonTech.Lottery.Web.ServiceLotteryLookup.LotteryGameDTO> GetLotteryGameAsync(int lotteryId) {
            return base.Channel.GetLotteryGameAsync(lotteryId);
        }
        
        public void DeleteLotteryGame(int lotteryId) {
            base.Channel.DeleteLotteryGame(lotteryId);
        }
        
        public System.Threading.Tasks.Task DeleteLotteryGameAsync(int lotteryId) {
            return base.Channel.DeleteLotteryGameAsync(lotteryId);
        }
        
        public void SaveLotteryGame(AstonTech.Lottery.Web.ServiceLotteryLookup.LotteryGameDTO gameToSave) {
            base.Channel.SaveLotteryGame(gameToSave);
        }
        
        public System.Threading.Tasks.Task SaveLotteryGameAsync(AstonTech.Lottery.Web.ServiceLotteryLookup.LotteryGameDTO gameToSave) {
            return base.Channel.SaveLotteryGameAsync(gameToSave);
        }
    }
}
